config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  namespace :admin do
    get "/dashboard", to: "dashboard#index"
    resources :user_roles, only: [:update]
    resources :campaign_managers, only: [:new, :create]
    resource  :candidates, path: ":candidate", as: :candidate,
              only: [:show, :edit, :update]
  end

  resources :candidate_issues, only: :update

  resources :two_factor_authentication, only: [:show, :update]

  resources :candidates, only: [:index, :show, :update]
  resources :issues, only: [:index, :show]
  resources :donations, only: [:create, :edit]
  resources :charges
  resources :orders, only: [:create, :show]


  get "/donations/undo", to: "donations#undo"

  get "/cart", to: "cart#show"
  patch "/cart/:id", to: "cart#update"
  delete "/cart/:id", to: "cart#destroy"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete"

  get "/join", to: "users#new"
  post "/join", to: "users#create"
  resources :user_roles, only: [:edit, :update]

  get "/profile", to: "users#show"
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :issues, through: :candidate_issues
  has_many :donations, through: :candidate_issues
  has_many :candidate_issues
  has_many :user_roles
  has_many :users, through: :user_roles
  validates :name, :bio, :party, presence: true
  validates :slug, uniqueness: true

  before_validation :generate_slug

  def generate_slug
    self.slug = name.parameterize
  end
end

app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController < ApplicationController
  include Admin::CandidatesHelper
  before_action :set_candidate, :set_slug

  def show
    @donations_by_date = DonationChart.donation_by_date(set_candidate)
    @donations_by_issue = DonationChart.donations_by_issue(set_candidate)
  end

  def edit
  end

  def update
  end

  private

  def set_candidate
    if current_user.user_roles.first.role_id == 2
      current_candidate
    else
      @current_candidate ||= Candidate.find_by(slug: params[:candidate])
    end
  end

  def set_slug
    if current_user.user_roles.first.role_id == 2 &&
       Candidate.find_by(slug: params[:candidate]) != current_candidate
      redirect_to admin_candidate_path(current_candidate.slug)
    else
      @current_candidate = Candidate.find_by(slug: params[:candidate])
    end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @democrats = Candidate.where(party: "Democratic")
    @republicans = Candidate.where(party: "Republican")
  end

  def show
    @candidate = candidate
    @registered = current_user.registered_user? if current_user
    @tweet_uri = TwitterService.new.first_tweet_link(@candidate.twitter_handle)
    @embedded_tweet = TwitterEmbed.new.embedded_tweet(@tweet_uri)
  end

  def update
    if candidate.update(candidate_params)
      flash[:success] = "Bio Successfully Updated"
      redirect_to edit_admin_candidate_path(candidate: candidate.slug)
    else
      flash[:errors] = "Do you even American Bro?"
      redirect_to edit_admin_candidate_path(candidate: candidate.slug)
    end
  end

  private

  def candidate_params
    params.require(:candidate).permit(:bio)
  end

  def candidate
    Candidate.find(params[:id])
  end
end

app/helpers/admin/candidates_helper.rb
module Admin::CandidatesHelper

  def goals
    @current_candidate.candidate_issues.map do |candidate_issue|
      candidate_issue.goal
    end
  end

  def total_goal
    goals.reduce(:+)
  end

  def campaign_raised_total
    @current_candidate.candidate_issues.inject(0) {|sum, x| sum + candidate_issue_raised_total(x)}
  end

  def campaign_percent_calculation
    campaign_raised_total.to_f / total_goal.to_f * 100
  end

  def campaign_progress_bar_percentage
    if campaign_percent_calculation.nan?
      0
    elsif campaign_percent_calculation > 100
      100
    else
      campaign_percent_calculation
    end
  end
end

app/views/admin/candidates/edit.html.erb
<header id="myCarousel" class="carousel slide">
  <div class="fill" id="slider-1"></div>
</header>

<br>
<div class="row" align="center" id="flash_messages">
<br>
  <div class="col-md-12" id="flash_notice">
   <%= render partial: "layouts/flashes" %>
  </div>
</div>
<br>

<div class="container">
  <div class="row">
    <h1 class="page-header" id="title-1"><%= link_to @current_candidate.name, candidate_path(@current_candidate) %></h1>
  </div>
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <%= bootstrap_form_for @current_candidate, url: "/candidates/#{@current_candidate.id}", method: :patch do |f| %>
        <%= f.text_field :bio %>
        <%= f.submit "Update Bio" %>
      <% end %>
    </div>
  </div>

  <div class="col-md-4 col-md-offset-4 portfolio-item">
     <%= image_tag("#{@current_candidate.last_name}.jpg",
         class: "img-responsive img-portfolio",
            id: "#{@current_candidate.last_name}-image") %>
  </div>
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2" id="stances">
      <% @current_candidate.candidate_issues.each do |candidate_issue| %>
        <h4><%= candidate_issue.topic %></h4>
        <%= bootstrap_form_for candidate_issue, method: :patch do |f| %>
          <%= f.text_field :stance %>
          <%= f.submit "Update Stance" %>
        <% end %>
        <br>
        <%= bootstrap_form_for candidate_issue, method: :patch do |f| %>
          <%= f.text_field :goal %>
          <%= f.submit "Update Goal" %>
        <% end %>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/candidates/show.html.erb
<head>
<script type="text/javascript"
        src="https://www.google.com/jsapi?autoload={
          'modules':[{
            'name':'visualization',
            'version':'1',
            'packages':['corechart']
          }]
        }"></script>

  <script type="text/javascript">
    google.setOnLoadCallback(drawChart);
    function drawChart() {
      var donationsByDate = <%= raw @donations_by_date %>;
      var data = new google.visualization.DataTable();
      data.addColumn('date', 'Date');
      data.addColumn('number', 'Amount');
      data.addRows(donationsByDate);

      var options = {
        title: 'Donations Over Time',
        curveType: 'function',
        legend: 'none',
        hAxis: {
          viewWindowMode: 'pretty',
        }
      };

      var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

      chart.draw(data, options);
    }
  </script>

  <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var donationsByIssue = <%= raw @donations_by_issue %>;
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Issue');
        data.addColumn('number', 'Amount');
        data.addRows(donationsByIssue);

        var options = {
          title: 'Donations by Issue'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
  </script>

</head>
<br>
<h3 id='title-2'><%= current_candidate.name %>'s Campaign Manager Dashboard</h3>
<br>
<div class="col-md-offset-2 col-md-4" id="browse-issues-button">
  <%= link_to "Candidate Stances and Goals", edit_admin_candidate_path(id: current_candidate.id), class: "btn btn-lg btn-default btn-block btn btn-danger" %>
</div>
<div class="col-md-4" id="browse-issues-button">
  <%= link_to "Add a Campaign Manager", new_admin_campaign_manager_path, class: "btn btn-lg btn-default btn-block btn btn-danger" %>
</div>

<div class="container" id="dashboard-stats">
  <div class="col-md-6 chart-bottom" id="curve_chart" style="text-center width:800px; height: 500px"></div>
  <div class="col-md-6 chart-bottom" id="piechart" style="width: 500px; height: 500px;"></div>
  <div class="col-lg-8 col-lg-offset-2">
    <div class="row">
      <h3 id="subtitle-2">Total Funded</h3>
      <div class="progress">
        <div class="progress-bar progress-bar-danger" roll="progressbar"
             aria-valuenow="<%= campaign_raised_total %>"
             aria-valuemin="0" aria-valuemax="<%= total_goal %>"
             style="min-width: 3em; max-width: 100%; width: <%= campaign_raised_total.to_f /
                    total_goal.to_f * 100 %>%;">
             <%= campaign_progress_bar_percentage.to_i %>%
        </div>
      </div>
      <div class="text-center">
        <h3 id="subtitle-2"><%= "#{number_to_currency(campaign_raised_total)} of
            #{number_to_currency(total_goal)}" %></h3>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-8 col-lg-offset-2">
  <div class="row">
    <% current_candidate.candidate_issues.each do |candidate_issue| %>
      <div class="list-group-item" id="candidate_issue-<%= candidate_issue.id %>">
        <div class="text-center">
          <h4><%= candidate_issue.topic %></h4>
        </div>
        <%= render partial: "layouts/progress_bar",
                    locals: {candidate_issue: candidate_issue} %>
      </div>
    <% end %>
  </div>
</div>