config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  namespace :admin do
    get "/dashboard", to: "dashboard#index"
    resources :user_roles, only: [:update]
    resources :campaign_managers, only: [:new, :create]
    resource  :candidates, path: ":candidate", as: :candidate,
              only: [:show, :edit, :update]
  end

  resources :candidate_issues, only: :update

  resources :two_factor_authentication, only: [:show, :update]

  resources :candidates, only: [:index, :show, :update]
  resources :issues, only: [:index, :show]
  resources :donations, only: [:create, :edit]
  resources :charges
  resources :orders, only: [:create, :show]


  get "/donations/undo", to: "donations#undo"

  get "/cart", to: "cart#show"
  patch "/cart/:id", to: "cart#update"
  delete "/cart/:id", to: "cart#destroy"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete"

  get "/join", to: "users#new"
  post "/join", to: "users#create"
  resources :user_roles, only: [:edit, :update]

  get "/profile", to: "users#show"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @featured_candidates = Candidate.where(featured: true)
    @issues = Issue.where(featured: true)
  end
end

app/views/welcome/index.html.erb
<!-- Header Carousel -->
<header id="myCarousel" class="carousel slide">
		<!-- Indicators -->
		<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner">
				<div class="item active">
						<div class="fill" id="slider-1">
			 			</div>
				</div>
				<div class="item">
						<div class="fill" id="slider-2"></div>
				</div>
				<div class="item" >
						<div class="fill" id="slider-3"></div>
				</div>
		</div>

		<!-- Controls -->
		<a class="left carousel-control" href="#myCarousel" data-slide="prev">
				<span class="icon-prev"></span>
		</a>
		<a class="right carousel-control" href="#myCarousel" data-slide="next">
				<span class="icon-next"></span>
		</a>
</header>

<div class="col-md-12" align="center" id="flash_notice">
	<br>
	<%= flash_messages %>
</div>

<!-- Page Content -->
<div class="container">
<br>
<div class="panel">
	<div class="panel-body">
		<div class="col-md-12">
			<div class="page-header">
				<h1 id='title-1'>Welcome to Earforked</h1>
				<h3 id='subtitle-1'>A Platform for Issue Specific Donating</h3>
			</div>
		</div>
	</div>
<!-- </div> -->

		<!-- Welcome Section -->
<!-- <div class="panel"> -->
	<div class="panel-body">
		<div class="col-md-12">
			<p id="header-intro">
					Earforked is a tool that will revolutionize how people donate to presidential elections. Earforked is unique because it allows users to donate to specific issues in each candidate's campaign. Do you like Hillary Clinton's stance on the environment? Donate to just that part of her campaign. Would you like to see each candidate's stance on the economy? Browse the Issues Section to see what each candidate thinks.
			</p>
		</div>
	</div>
</div>
		<!-- Candidate Section -->
<div class="panel">
	<div class="panel-body" id="candidates">
		<div class="col-lg-12">
			<h2 class="page-header"> Top Candidates</h2>
		</div>
		<% @featured_candidates.each do |candidate| %>
			<div class="col-md-4 col-sm-4">
				<a href="portfolio-item.html">
					<%= link_to image_tag("#{candidate.last_name}.jpg", class:"img-responsive img-portfolio img-hover", id:"candidate-#{candidate.id}"), candidate_path(candidate.id)%>
	 			</a>
				<h4 id="candidate-front-title"><%= link_to candidate.name, candidate_path(candidate.id) %></h4>
			</div>
		<% end %>
	</div>
</div>
		<!-- Issue Section -->
<div class="panel">
	<div class="panel-body" id="issues">
		<div class="col-lg-12">
			<h2 class="page-header"> Top Issues</h2>
		</div>
		<% @issues.each do |issue| %>
			<div class="col-md-4 col-sm-6">
				<a href="portfolio-item.html">
					<%= link_to image_tag("#{issue.picture}.jpg", class:"img-responsive img-portfolio img-hover", id:"issue-#{issue.id}"), issue_path(issue.id) %>
				</a>
				<h4 id="issue-front-title"><%= link_to issue.topic, issue_path(issue.id) %></h4>
			</div>
		<% end %>
	</div>
</div>
		<!-- /.row -->

		<!-- Call to Action Section -->
		<div class="panel-body" id="button-front-page">
				<!-- <div class="row"> -->
						<div class="col-md-offset-2 col-md-4" id="browse-candidates-button">
								<%= link_to "Browse All 2016 Candidates", candidates_path, class: "btn btn-lg btn-default btn-block btn btn-primary front-button" %>
						</div>
						<div class="col-md-4" id="browse-issues-button">
								<%= link_to "Browse All 2016 Issues", issues_path, class: "btn btn-lg btn-default btn-block btn btn-primary front-button" %>
						</div>
				<!-- </div> -->
		</div>


		<% unless current_user %>
		<div class="panel-body">
				<div class="col-md-offset-4 col-md-4" id="login-button">
						<%= link_to "Login", login_path, class: "btn-lg btn btn-lg btn-default btn-block btn btn-danger" %>
				</div>
		</div>
		<% end %>
	<div class="panel-body">
		<div class="col-md-12" id="clockdiv">
				<h3 id='subtitle-2'>Countdown till the Election</h3>

					<div>
						<span class="days"></span>
						<div class="smalltext">Days</div>
					</div>

					<div>
						<span class="hours"></span>
						<div class="smalltext">Hours</div>
					</div>

					<div>
						<span class="minutes"></span>
						<div class="smalltext">Minutes</div>
					</div>

					<div>
						<span class="seconds"></span>
						<div class="smalltext">Seconds</div>
					</div>
				</div>
			</div>
		<!-- /.row -->
		<!-- Footer -->
</div>

<script type="text/javascript">
$('.carousel').carousel({
  		interval: 5000 //changes the speed
  })
</script>