config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  namespace :admin do
    get "/dashboard", to: "dashboard#index"
    resources :user_roles, only: [:update]
    resources :campaign_managers, only: [:new, :create]
    resource  :candidates, path: ":candidate", as: :candidate,
              only: [:show, :edit, :update]
  end

  resources :candidate_issues, only: :update

  resources :two_factor_authentication, only: [:show, :update]

  resources :candidates, only: [:index, :show, :update]
  resources :issues, only: [:index, :show]
  resources :donations, only: [:create, :edit]
  resources :charges
  resources :orders, only: [:create, :show]


  get "/donations/undo", to: "donations#undo"

  get "/cart", to: "cart#show"
  patch "/cart/:id", to: "cart#update"
  delete "/cart/:id", to: "cart#destroy"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete"

  get "/join", to: "users#new"
  post "/join", to: "users#create"
  resources :user_roles, only: [:edit, :update]

  get "/profile", to: "users#show"
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :issues, through: :candidate_issues
  has_many :donations, through: :candidate_issues
  has_many :candidate_issues
  has_many :user_roles
  has_many :users, through: :user_roles
  validates :name, :bio, :party, presence: true
  validates :slug, uniqueness: true

  before_validation :generate_slug

  def generate_slug
    self.slug = name.parameterize
  end
end

app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController < ApplicationController
  include Admin::CandidatesHelper
  before_action :set_candidate, :set_slug

  def show
    @donations_by_date = DonationChart.donation_by_date(set_candidate)
    @donations_by_issue = DonationChart.donations_by_issue(set_candidate)
  end

  def edit
  end

  def update
  end

  private

  def set_candidate
    if current_user.user_roles.first.role_id == 2
      current_candidate
    else
      @current_candidate ||= Candidate.find_by(slug: params[:candidate])
    end
  end

  def set_slug
    if current_user.user_roles.first.role_id == 2 &&
       Candidate.find_by(slug: params[:candidate]) != current_candidate
      redirect_to admin_candidate_path(current_candidate.slug)
    else
      @current_candidate = Candidate.find_by(slug: params[:candidate])
    end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @democrats = Candidate.where(party: "Democratic")
    @republicans = Candidate.where(party: "Republican")
  end

  def show
    @candidate = candidate
    @registered = current_user.registered_user? if current_user
    @tweet_uri = TwitterService.new.first_tweet_link(@candidate.twitter_handle)
    @embedded_tweet = TwitterEmbed.new.embedded_tweet(@tweet_uri)
  end

  def update
    if candidate.update(candidate_params)
      flash[:success] = "Bio Successfully Updated"
      redirect_to edit_admin_candidate_path(candidate: candidate.slug)
    else
      flash[:errors] = "Do you even American Bro?"
      redirect_to edit_admin_candidate_path(candidate: candidate.slug)
    end
  end

  private

  def candidate_params
    params.require(:candidate).permit(:bio)
  end

  def candidate
    Candidate.find(params[:id])
  end
end

app/helpers/admin/candidates_helper.rb
module Admin::CandidatesHelper

  def goals
    @current_candidate.candidate_issues.map do |candidate_issue|
      candidate_issue.goal
    end
  end

  def total_goal
    goals.reduce(:+)
  end

  def campaign_raised_total
    @current_candidate.candidate_issues.inject(0) {|sum, x| sum + candidate_issue_raised_total(x)}
  end

  def campaign_percent_calculation
    campaign_raised_total.to_f / total_goal.to_f * 100
  end

  def campaign_progress_bar_percentage
    if campaign_percent_calculation.nan?
      0
    elsif campaign_percent_calculation > 100
      100
    else
      campaign_percent_calculation
    end
  end
end

app/views/candidates/_apply_campaign_manager_modal.html.erb
<div class="modal fade" id="applyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Apply To Be A Campaign Manager Below</h4>
    </div>
    <div class="modal-body">
      <%= bootstrap_form_for current_user_role, url: user_role_path do |f| %>
        <%= f.text_field :reason, help: "Please describe why you'd be a good campaign manager for #{candidate.name}" %>
        <%= f.hidden_field :candidate_id, :value => candidate.id %>
        <%= f.submit "Save changes" %>
      <% end %>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/candidates/_candidate_issue_row.html.erb
<div class="donation-candidate">
  <h3><span class="glyphicon glyphicon-plus-sign"></span> <%= candidate_issue.topic %></h3>
  <div style="margin-left: 32px;"><h4><%= candidate_issue.stance %></h4></div>
</div>

<div class="donation-time">
  <div id="row-donate-form">
    <%= bootstrap_form_for Donation.new, url: donations_path do |f| %>
      <%= f.hidden_field :candidate_issue_id, value: candidate_issue.id %>
      <%= f.number_field :amount, prepend: "$", in: 1.0..2700.0, step: 1.0 %>
      <%= f.hidden_field :candidate_id, value: candidate_issue.candidate_id %>
      <%= f.hidden_field :origin_page, value: candidate_path(candidate_issue.candidate_id) %>
      <%= f.submit "Donate" %>
    <% end %>
  </div>
  <br>
  <%= render partial: "layouts/progress_bar",
              locals: {candidate_issue: candidate_issue} %>

  <br>
  <h4>Total Raised: <%= number_to_currency(candidate_issue_raised_total(candidate_issue.id)) %> Goal: <%= number_to_currency(candidate_issue.goal) %></h4>
</div>

app/views/candidates/index.html.erb
<br>
<div class="container" id="candidates">
  <div class="panel">
    <div class="panel-body">
      <div class="col-lg-12">
         <h1 id="title-2">Candidates</h1>
         <h3 id="subtitle-1">Presidential hopefuls for the 2016 Election</h3>
      </div>
    </div>
  </div>

  <div class="panel">
    <div class="panel-body">
      <h2 align="center" id="index-titles">Republicans</h2><br>
      <% @republicans.each do |candidate| %>
        <div class="col-md-4 portfolio-item">
          <a>
            <%= link_to image_tag("#{candidate.last_name}.jpg",
            class:"img-responsive img-portfolio img-hover",
            id:"#{candidate.last_name}-image"),
            candidate_path(candidate) %>
          </a>
          <h3>
             <%= link_to candidate.name, candidate_path(candidate), id: "index-names" %>
          </h3>
          <p><%= candidate.bio %></p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="panel">
    <div class="panel-body">
      <h2 align="center" id="index-titles">Democrats</h2><br>
      <% @democrats.each do |candidate| %>
       <div class="col-md-4 portfolio-item">
           <a>
               <%= link_to image_tag("#{candidate.last_name}.jpg",
               class: "img-responsive img-portfolio img-hover",
               id: "#{candidate.last_name}-image"),
               candidate_path(candidate) %>
           </a>
           <h3>
            <%= link_to candidate.name, candidate_path(candidate), id: "index-names" %>
           </h3>
           <p><%= candidate.bio %></p>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/candidates/show.html.erb
<header id="myCarousel" class="carousel slide">
  <div class="fill" id="slider-1"></div>
</header>

<div class="row" align="center">
  <br>
    <div class="col-md-12" id="flash_notice">
    <%= flash_messages %>
    </div>
</div><br>

<div class="container">
  <div class="row">
    <h1 class="page-header" id="title-1"><%= @candidate.name %></h1>
  </div>
  <div class="row">
    <div class="col-lg-5 portfolio-item">
       <%= image_tag("#{@candidate.last_name}.jpg",
           class: "img-responsive img-portfolio",
              id: "#{@candidate.last_name}-image") %>

      <div class="panel">
        <div class="panel-body">
          <p id="header-intro"><%= @candidate.bio %></p>
        </div>
      </div>

      <div class="portfolio-item">
        <%= @embedded_tweet["html"].html_safe %>
      </div>
    </div>
    <div class="col-lg-7" id="stances">
      <% @candidate.candidate_issues.each do |candidate_issue| %>
        <div class="list-group-item" id="candidate_issue-<%= candidate_issue.id %>">
          <%= render partial: "candidate_issue_row",
                      locals: {candidate_issue: candidate_issue} %>
        </div>
      <% end %>
    </div>
  <!-- </div> -->
  <!-- <br> -->
  <!-- <div class="row"> -->
    <div class="col-lg-6">

    </div>
  </div>
  <!-- <div class="container"> -->

  <!-- </div> -->
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 text-center">
      <% if @registered %>
        <h3>Believe in what you've read?<br>
            Passionate about this particular candidate?<br>
            Apply to become their campaign manager today!</h3>
          <div class="text-center">
            <button type="button" class="btn btn-danger btn-lg" data-toggle="modal"
                  data-target="#applyModal">
                  Apply Now
            </button>
          </div>
          <%= render partial: "apply_campaign_manager_modal",
                     locals: {candidate: @candidate}%>
      <% elsif !current_user %>
      <br><br>
      <h3>Believe in what you've read?<br>
          Passionate about this particular candidate?<br>
          Apply to become their campaign manager today!</h3>
        <%= link_to "Login to Apply Now", login_path, class: "btn btn-danger btn-lg" %>
      <% end %>
    </div>
  </div>
</div>

<br><br>