config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  namespace :admin do
    get "/dashboard", to: "dashboard#index"
    resources :user_roles, only: [:update]
    resources :campaign_managers, only: [:new, :create]
    resource  :candidates, path: ":candidate", as: :candidate,
              only: [:show, :edit, :update]
  end

  resources :candidate_issues, only: :update

  resources :two_factor_authentication, only: [:show, :update]

  resources :candidates, only: [:index, :show, :update]
  resources :issues, only: [:index, :show]
  resources :donations, only: [:create, :edit]
  resources :charges
  resources :orders, only: [:create, :show]


  get "/donations/undo", to: "donations#undo"

  get "/cart", to: "cart#show"
  patch "/cart/:id", to: "cart#update"
  delete "/cart/:id", to: "cart#destroy"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete"

  get "/join", to: "users#new"
  post "/join", to: "users#create"
  resources :user_roles, only: [:edit, :update]

  get "/profile", to: "users#show"
end

app/views/layouts/_campaign_manager_navbar.html.erb
<li>
  <a href="/profile" id="hovered">
    <%= current_user.first_name %>
  </a>
</li>
<li>
  <%= link_to "#{current_candidate.name} Dashboard",
      admin_candidate_path(current_candidate.slug), id: "hovered" %>
</li>
<li>
  <%= link_to "Logout", logout_path, method: :delete, id: "hovered" %>
</li>

app/views/layouts/_flashes.html.erb
<% flash.each do |name, message| %>
  <%= content_tag(:div, sanitize(message),
  class: "alert alert-success fade-in",
  :id => "flash_#{name}") %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="page-header">
</div>

<footer id="header-intro">
  <div class="row">
    <div class="col-lg-12" id="copyright">
      <p>Copyright &copy; Earforked 2015</p>
    </div>
  </div>
</footer>

app/views/layouts/_guest_navbar.html.erb
<li>
  <%= link_to "Join", join_path, id: "hovered" %>
</li>
<li>
  <%= link_to "Login", login_path, id: "hovered" %>
</li>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top"
     role="navigation"
     id="navbar-flash">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button"
                    class="navbar-toggle"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Earforked", root_path, class: "navbar-brand", id: "logo" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Candidates", candidates_path, id: "hovered" %><span class="sr-only">(current)</span></li>
          <li><%= link_to "Issues", issues_path, id: "hovered" %><span class="sr-only">(current)</span></li>
        </ul>
        <ul class="nav navbar-nav navbar-right" id="navbar">
          <li id="cart">
            <%= link_to cart_path, class: "cart", id: "hovered" do %>
              <span class="glyphicon glyphicon-shopping-cart"></span>
              <%= "Cart: $" + cart.total.to_s if cart.total %>
            <% end %>
          </li>
          <% if platform_admin? %>
            <%= render "layouts/platform_admin_navbar" %>
          <% elsif campaign_manager? %>
            <%= render "layouts/campaign_manager_navbar" %>
          <% elsif registered_user? %>
            <%= render "layouts/registered_user_navbar" %>
          <% else %>
            <%= render "layouts/guest_navbar" %>
          <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_platform_admin_navbar.html.erb
<li>
  <a href="/profile" id="hovered">
    <%= current_user.first_name %>
  </a>
</li>
<li>
  <%= link_to "Dashboard", admin_dashboard_path, id: "hovered" %>
</li>
<li>
  <%= link_to "Logout", logout_path, method: :delete, id: "hovered" %>
</li>

app/views/layouts/_platform_manager_navbar.html.erb
<li>
  <a href="/profile">
    <%= "Welcome, #{current_user.username}." %>
  </a>
</li>
<li>
  <%= link_to "Dashboard", dashboard_path %>
</li>
<li>
  <%= link_to "Logout", logout_path, method: :delete %>
</li>

app/views/layouts/_progress_bar.html.erb
<div class="progress">
  <div class="progress-bar progress-bar-danger" roll="progressbar"
       aria-valuenow="<%= candidate_issue_raised_total(candidate_issue.id) %>"
       aria-valuemin="0" aria-valuemax="<%= candidate_issue.goal %>"
       style="min-width: 3em; max-width: 100%; width: <%= candidate_issue_raised_total(candidate_issue.id).to_f /
              candidate_issue.goal.to_f * 100 %>%;">
       <%= progress_bar_percentage(candidate_issue) %>%
  </div>
</div>

app/views/layouts/_registered_user_navbar.html.erb
<li>
  <a href="/profile" id="hovered">
    <%= current_user.first_name %>
  </a>
</li>
<li>
  <%= link_to "Logout", logout_path, method: :delete, id: "hovered" %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Earforked - A Site for Issue Specific Donating</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
   <link href='https://fonts.googleapis.com/css?family=Quattrocento:700'
         rel='stylesheet'
         type='text/css'>
  </head>
  <body>
    <!-- <div id="wrapper"> -->
      <%= render 'layouts/navbar' %>

      <script type="text/javascript"
              src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5626b1e9bbc5352d"
              async="async"></script>

      <%= yield %>

      <%= render 'layouts/footer' %>

    <!-- </div> -->
  </body>
</html>